config/routes.rb
Temperaturemonitor::Application.routes.draw do
  root :to => 'temperature_sensors#graph'

  get "temperature_sensors/index"

  get "temperature_sensors/new"

  get "temperature_sensors/show"

  get "temperature_sensors/delete"

  get "temperature_sensors/create"

  get "temperature_sensors/edit"

  get "temperature_sensors/update"

  get "temperature_sensors/graph"

  resources :temperature_sensors

end

app/models/temperature_sensor.rb
class TemperatureSensor < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/temperature_sensors_controller.rb
class TemperatureSensorsController < ApplicationController
  # GET /temperature_sensors
  # GET /temperature_sensors.json
  def index
    # @temperature_sensors = TemperatureSensor.last(12)
    @temperature_sensors = TemperatureSensor.where(:address => "10 F6 BD 25 2 8 0 50")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @temperature_sensors }
    end
  end

  # GET /temperature_sensors/1
  # GET /temperature_sensors/1.json
  def show
    @temperature_sensor = TemperatureSensor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @temperature_sensor }
    end
  end

  # GET /temperature_sensors/new
  # GET /temperature_sensors/new.json
  def new
    @temperature_sensor = TemperatureSensor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @temperature_sensor }
    end
  end

  # GET /temperature_sensors/1/edit
  def edit
    @temperature_sensor = TemperatureSensor.find(params[:id])
  end

  # POST /temperature_sensors
  # POST /temperature_sensors.json
  def create
    @temperature_sensor = TemperatureSensor.new(params[:temperature_sensor])

    respond_to do |format|
      if @temperature_sensor.save
        format.html { redirect_to @temperature_sensor, :notice => 'Temperature sensor was successfully created.' }
        format.json { render :json => @temperature_sensor, :status => :created, :location => @temperature_sensor }
      else
        format.html { render :action => "new" }
        format.json { render :json => @temperature_sensor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /temperature_sensors/1
  # PUT /temperature_sensors/1.json
  def update
    @temperature_sensor = TemperatureSensor.find(params[:id])

    respond_to do |format|
      if @temperature_sensor.update_attributes(params[:temperature_sensor])
        format.html { redirect_to @temperature_sensor, :notice => 'Temperature sensor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @temperature_sensor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /temperature_sensors/1
  # DELETE /temperature_sensors/1.json
  def destroy
    @temperature_sensor = TemperatureSensor.find(params[:id])
    @temperature_sensor.destroy

    respond_to do |format|
      format.html { redirect_to temperature_sensors_url }
      format.json { head :ok }
    end
  end

  def graph
    @sensor1 = TemperatureSensor.where(:address => "10 F6 BD 25 2 8 0 50")
    @sensor1 = @sensor1.map { |i| "[" + "%d000"%i.time.to_i + "," + i.temperature.to_s + "]" }.join(",")
    @sensor1 = "["+@sensor1+"]"
    @sensor1 = "[[]]"

    @sensor2 = TemperatureSensor.where(:address => "10 4F C4 25 2 8 0 5F")
    @sensor2 = @sensor2.map { |i| "[" + "%d000"%i.time.to_i + "," + i.temperature.to_s + "]" }.join(",")
    @sensor2 = "["+@sensor2+"]"
    respond_to do |format|
      format.html
      format.json { render :json => @sensor1 }
      format.json { render :json => @sensor2 }
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/temperature_sensors_helper.rb
module TemperatureSensorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Temperaturemonitor</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/temperature_sensors/_form.html.erb
<%= form_for(@temperature_sensor) do |f| %>
  <% if @temperature_sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temperature_sensor.errors.count, "error") %> prohibited this temperature_sensor from being saved:</h2>

      <ul>
      <% @temperature_sensor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br />
    <%= f.text_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temperature_sensors/create.html.erb
<h1>TemperatureSensors#create</h1>
<p>Find me in app/views/temperature_sensors/create.html.erb</p>

app/views/temperature_sensors/delete.html.erb
<h1>TemperatureSensors#delete</h1>
<p>Find me in app/views/temperature_sensors/delete.html.erb</p>

app/views/temperature_sensors/edit.html.erb
<h1>Editing temperature_sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @temperature_sensor %> |
<%= link_to 'Back', temperature_sensors_path %>

app/views/temperature_sensors/graph.html.erb
<meta http-equiv="refresh" content="120" />

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script type="text/javascript" src="../highstock-1.0.2/js/highstock.js"></script>
<script type="text/javascript" src="../highstock-1.0.2/js/modules/exporting.js"></script>

<script type="text/javascript">
  $(function() {
  
  // Create the chart
  window.chart = new Highcharts.StockChart({
  chart : {
  renderTo : 'container'
  },
  
  rangeSelector : {
  buttons: [{
  type:'minute',
  count: 60,
  text:'1h'
  }, {
  type:'minute',
  count: 720,
  text:'12h'
  }, {
  type:'minute',
  count: 1440,
  text:'1d'
  }, {
  type:'minute',
  count: 10080,
  text:'7d'
  }, {
  type: 'month',
  count: 1,
  text: '1m'
  }, {
  type: 'month',
  count: 3,
  text: '3m'
  }, {
  type: 'month',
  count: 6,
  text: '6m'
  }, {
  type: 'ytd',
  text: 'YTD'
  }, {
  type: 'year',
  count: 1,
  text: '1y'
  }, {
  type: 'all',
  text: 'All'
  }],
  selected : 2
  },
 
  title : {
  text : 'Rob\'s Temperature Graph'
  },
  
  xAxis : {
  //maxZoom : 14 * 24 * 3600000 // fourteen days
  maxZoom : 1 * 3600000
  },

  yAxis : {
  min: 20,
  max: 90,
  title : {
  text : 'Temperature (F)'
  }
  },
  
  series : [{
  name : 'Garage Sensor 1',
  data : <%= @sensor1 %>,
    tooltip: {
      yDecimals: 1
    }
  },{
  name : 'Garage Sensor 2',
  data : <%= @sensor2 %>,
    tooltip: {
      yDecimals: 1
    }
  }
  ]

  });  
  });  
</script>

<div id="container" style="height: 500px; min-width: 500px"></div>

app/views/temperature_sensors/index.html.erb
<h1>Listing Last 10 Sensor Readings</h1>

<table border="1">
  <tr>
    <th>Address</th>
    <th>Temperature</th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @temperature_sensors.each do |temperature_sensor| %>
  <tr>
    <td><%= temperature_sensor.address %></td>
    <td><%= temperature_sensor.temperature %></td>
    <td><%= temperature_sensor.time %></td>
    <td><%= link_to 'Show', temperature_sensor %></td>
    <td><%= link_to 'Edit', edit_temperature_sensor_path(temperature_sensor) %></td>
    <td><%= link_to 'Destroy', temperature_sensor, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Temperature Sensor Measurement', new_temperature_sensor_path %>

app/views/temperature_sensors/new.html.erb
<h1>New temperature_sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', temperature_sensors_path %>

app/views/temperature_sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @temperature_sensor.address %>
</p>

<p>
  <b>Temperature:</b>
  <%= @temperature_sensor.temperature %>
</p>

<p>
  <b>Time:</b>
  <%= @temperature_sensor.time %>
</p>


<%= link_to 'Edit', edit_temperature_sensor_path(@temperature_sensor) %> |
<%= link_to 'Back', temperature_sensors_path %>

app/views/temperature_sensors/update.html.erb
<h1>TemperatureSensors#update</h1>
<p>Find me in app/views/temperature_sensors/update.html.erb</p>